sonar.projectKey=tp-jenkins
sonar.organization=ton_organisation
sonar.projectName=TP-Jenkins
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.login=squ_b6ddcfcc7c46ed5ca3a3432f9ad10b890988df43
